service: hello

frameworkVersion: ">=1.56.1"

provider:
  name: aws
  stage: dev
  region: eu-central-1
  tracing:
    lambda: true

package:
  individually: true

functions:
  helloJvm:
    runtime: java8
    handler: io.quarkus.amazon.lambda.runtime.QuarkusStreamHandler::handleRequest
    package:
      artifact: target/quarkus-lambda-native-2.0-SNAPSHOT-runner.jar
    events:
      - http:
          method: get
          path: jvm
  helloNative:
    runtime: provided
    handler: handler
    environment:
      DISABLE_SIGNAL_HANDLERS: true
    package:
      artifact: target/function.zip
    events:
      - http:
          method: get
          path: native
